### PR TITLE
Added simple descriptions to files missing descriptions 

### PR DESCRIPTION
**Pull request by scraggard**
Added simple descriptions/summary to the top of the files that did not have any descriptions/summary for:
1. test_class_objects.py
2. test_inheritance.py
3. test_method_objects.py
4. test_multiple_inheritance.py
5. test_file_methdos.py
6. test_file_reading.py
7. test_math.py

### CODE REVIEW

**Comment by trekhleb** [comment]
@scraggard  thank you for additional comments!
Could you please address the [pylint and flake issues](https://travis-ci.org/trekhleb/learn-python/builds/437436086?utm_source=github_status&utm_medium=notification) that make PR checks fail?

**Comment by scraggard** [comment]
Hi, I apologize about the trailing spaces that were giving an issue! It looks like it has cleared now.

Just a heads-up, it's a very minor thing but test_files_methdos.py looks like a typo for test_files_methods.py!

Thank you for letting me be a part of this! I believe that this is very useful for people learning python by giving them hands-on code.

**Comment by trekhleb** [comment]
@scraggard thanks for the good comments in code once again!
And also thank you for the pointing out to the typo in test_files_methdos.py filename. I'll change that just right after I merge your PR.

**Comment by trekhleb** [comment]
@scraggard the filename is fixed now as well.

**Pull request merged**
